### ISSUE TITLE
Submitter should retain same identify

### ISSUE THREAD

**Issue by AmberSJones** [UCHIC/CKANDev#89]
If a dataset is edited, the 'Submitter' changes to become the identity of the person who performed the edits. We need it to retain the same identity as the person who initially submitted the dataset. Not sure if this is a bug or default ckan behavior.

**Comment by pkdash** [comment]
This is a bug in our implementation. I have now fixed it. However, I have applied this patch to our sandbox server (http://iutah-ckan-test.uwrl.usu.edu). If @AmberSJones  can test it there and let me know if it works then I will update the production server.

**Comment by AmberSJones** [comment]
This seems to be addressed. Push to production.

**Comment by pkdash** [comment]
@AmberSJones the change I have made to fix this bug can potentially break few other things. That's why I didn't feel comfortable in applying the patch to the production server before testing thoroughly on the test server. The test should include creation of a new dataset, followed by an update of that dataset (update should include metadata update as well as dataset file update), update of an previously existing dataset (both metadata update and file update), and also setting  a datatset to private/public. If we pass these tests on the test server, I can then apply the patch to the production server.

**Comment by AmberSJones** [comment]
Ok- I can do some more thorough testing.

**Comment by AmberSJones** [comment]
I've tested all of the above cases. The 'Submitter' persists as the user that initially submitted the record.

**Comment by pkdash** [comment]
I have now updated the production site with this fix.

**Comment by AmberSJones** [comment]
I've tested this on the production server and am experiencing the original behavior.

**Comment by pkdash** [comment]
I may have to restart/shutdown the server for a short time to get it updated. Can I do that sometime this weekend?

**Comment by AmberSJones** [comment]
Should be fine.

**Comment by pkdash** [comment]
I did run a test on the production server and it seems to work. Try again and let me know.

**Comment by AmberSJones** [comment]
Looks good. I'm closing the issue.
